# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/etud/Bureau/InterfaceGraphique/projetTaquin

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/etud/Bureau/InterfaceGraphique/projetTaquin

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/etud/Bureau/InterfaceGraphique/projetTaquin/CMakeFiles /home/etud/Bureau/InterfaceGraphique/projetTaquin//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/etud/Bureau/InterfaceGraphique/projetTaquin/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named projet

# Build rule for target.
projet: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 projet
.PHONY : projet

# fast build rule for target.
projet/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projet.dir/build.make CMakeFiles/projet.dir/build
.PHONY : projet/fast

#=============================================================================
# Target rules for targets named projet_autogen

# Build rule for target.
projet_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 projet_autogen
.PHONY : projet_autogen

# fast build rule for target.
projet_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projet_autogen.dir/build.make CMakeFiles/projet_autogen.dir/build
.PHONY : projet_autogen/fast

game.o: game.cpp.o

.PHONY : game.o

# target to build an object file
game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projet.dir/build.make CMakeFiles/projet.dir/game.cpp.o
.PHONY : game.cpp.o

game.i: game.cpp.i

.PHONY : game.i

# target to preprocess a source file
game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projet.dir/build.make CMakeFiles/projet.dir/game.cpp.i
.PHONY : game.cpp.i

game.s: game.cpp.s

.PHONY : game.s

# target to generate assembly for a file
game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projet.dir/build.make CMakeFiles/projet.dir/game.cpp.s
.PHONY : game.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projet.dir/build.make CMakeFiles/projet.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projet.dir/build.make CMakeFiles/projet.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projet.dir/build.make CMakeFiles/projet.dir/main.cpp.s
.PHONY : main.cpp.s

projet_autogen/mocs_compilation.o: projet_autogen/mocs_compilation.cpp.o

.PHONY : projet_autogen/mocs_compilation.o

# target to build an object file
projet_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projet.dir/build.make CMakeFiles/projet.dir/projet_autogen/mocs_compilation.cpp.o
.PHONY : projet_autogen/mocs_compilation.cpp.o

projet_autogen/mocs_compilation.i: projet_autogen/mocs_compilation.cpp.i

.PHONY : projet_autogen/mocs_compilation.i

# target to preprocess a source file
projet_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projet.dir/build.make CMakeFiles/projet.dir/projet_autogen/mocs_compilation.cpp.i
.PHONY : projet_autogen/mocs_compilation.cpp.i

projet_autogen/mocs_compilation.s: projet_autogen/mocs_compilation.cpp.s

.PHONY : projet_autogen/mocs_compilation.s

# target to generate assembly for a file
projet_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projet.dir/build.make CMakeFiles/projet.dir/projet_autogen/mocs_compilation.cpp.s
.PHONY : projet_autogen/mocs_compilation.cpp.s

taquin.o: taquin.cpp.o

.PHONY : taquin.o

# target to build an object file
taquin.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projet.dir/build.make CMakeFiles/projet.dir/taquin.cpp.o
.PHONY : taquin.cpp.o

taquin.i: taquin.cpp.i

.PHONY : taquin.i

# target to preprocess a source file
taquin.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projet.dir/build.make CMakeFiles/projet.dir/taquin.cpp.i
.PHONY : taquin.cpp.i

taquin.s: taquin.cpp.s

.PHONY : taquin.s

# target to generate assembly for a file
taquin.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projet.dir/build.make CMakeFiles/projet.dir/taquin.cpp.s
.PHONY : taquin.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... projet_autogen"
	@echo "... projet"
	@echo "... game.o"
	@echo "... game.i"
	@echo "... game.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... projet_autogen/mocs_compilation.o"
	@echo "... projet_autogen/mocs_compilation.i"
	@echo "... projet_autogen/mocs_compilation.s"
	@echo "... taquin.o"
	@echo "... taquin.i"
	@echo "... taquin.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

